name: Release

on:
  push:
    tags:
      - "v*" # Trigger saat ada tag yang di-push, misalnya v1.1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %h %s (%an)" > changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1 # Menggunakan 'action-gh-release' sebagai alternatif yang mendukung 'token'
        with:
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Menyediakan token melalui environment variable
